version: "3"
services:
  password_vault:
    build: .
    ports:
      - "8000:8000"
    env_file: "./envs/.env.pw_vault"
    depends_on:
      - password_valut_database
    container_name: base_container
    volumes:
      - .:/code
      - media_volume:/code/media/
      - static_volume:/code/static/
    restart: always
    command: "python manage.py runserver 0.0.0.0:8000"

  password_valut_database:
    image: postgres
    container_name: database_container
    restart: always
    env_file: "./envs/.env.db"
    volumes:
      - database_volume:/var/lib/postgresql/data/

  adminer:
    image: adminer
    container_name: database_adminer_container
    restart: always
    ports:
      - "8080:8080"
volumes:
  database_volume:
  media_volume:
  static_volume:
