# Generated by Django 3.2.6 on 2021-08-04 11:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, help_text='Password ID', primary_key=True, serialize=False)),
                ('datas', models.JSONField()),
                ('data_note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
