# Generated by Django 3.2.6 on 2021-08-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='datas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
