# Generated by Django 3.2.6 on 2021-08-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_password_datas'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
