# Generated by Django 3.2.6 on 2021-08-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_password_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='title',
            field=models.CharField(default='', max_length=400),
        ),
    ]
