# Generated by Django 3.2.6 on 2021-08-04 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0008_password_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Data_User', to='auth.user'),
            preserve_default=False,
        ),
    ]
